netgen_openweather_weather_by_geographic_coordinates:
    path: /netgen/openweather/weather/coordinates/{latitude}/{longitude}
    defaults: { _controller: 'netgen_open_weather_map.controller.weather:byGeographicCoordinates' }
    methods:
        - GET
    requirements:
        latitude: \d+
        longitude: \d+

netgen_openweather_weather_by_city_name:
    path: /netgen/openweather/weather/cityname/{cityName}/{countryCode}
    defaults: { _controller: 'netgen_open_weather_map.controller.weather:byCityName', countryCode: '' }
    methods:
        - GET
    requirements:
        cityName: \w+
        countryCode: \w+

netgen_openweather_weather_by_city_id:
    path: /netgen/openweather/weather/cityid/{cityId}
    defaults: { _controller: 'netgen_open_weather_map.controller.weather:byCityId' }
    methods:
        - GET
    requirements:
        cityId: \d+

netgen_openweather_weather_by_zip_code:
    path: /netgen/openweather/weather/zipcode/{zipCode}/{countryCode}
    defaults: { _controller: 'netgen_open_weather_map.controller.weather:byZipCode', countryCode: '' }
    methods:
        - GET
    requirements:
        zipCode: \d+
        countryCode: \w+

netgen_openweather_weather_by_rectangle_zone:
    path: /netgen/openweather/weather/rectanglezone/{longitudeLeft}/{latitudeBottom}/{logitudeRight}/{latitudeTop}/{cluster}
    defaults: { _controller: 'netgen_open_weather_map.controller.weather:byRectangleZone' }
    methods:
        - GET
    requirements:
        longitudeLeft: \d+
        latitudeBottom: \d+
        logitudeRight: \d+
        latitudeTop: \d+
        cluster: \w+

netgen_openweather_weather_by_circle:
    path: /netgen/openweather/weather/circle/{latitude}/{longitude}/{cluster}/{numberOfCities}
    defaults: { _controller: 'netgen_open_weather_map.controller.weather:byCircle' }
    methods:
        - GET
    requirements:
        latitude: \d+
        longitude: \d+
        cluster: \w+
        numberOfCities: \d+

netgen_openweather_weather_by_city_ids:
    path: /netgen/openweather/weather/cityids
    defaults: { _controller: 'netgen_open_weather_map.controller.weather:byCityIds' }
    methods:
        - GET
