language: php

cache:
    directories:
        - vendor

matrix:
    # mark as finished before allow_failures are run
    fast_finish: true
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0

# test only master (+ pull requests)
branches:
  only:
    - master

# make sure to update composer to latest available version
before_install:
    - phpenv config-rm xdebug.ini
    - which composer
    - composer self-update

# install dependencies
install: php -d memory_limit=-1 /usr/local/bin/composer install --prefer-source -o

# execute phpunit as the script command
script:
  - ./vendor/bin/phpunit -d memory_limit=-1 --colors -c phpunit.xml

# disable mail notifications
notification:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30

# we don't need sudo
sudo: false
